name: Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]

permissions:
    contents: read

jobs:
    pull-request:
        name: Pull Request
        uses: NixySoftware/.github/.github/workflows/commits.yml@e4cce7beed9cf44052c57e416e15cc25f6617eb8
